whole:
  # train
  epochs: 100
  lr: 0.01
  weight_decay: 0.0001
  momentum: 0.9
  use_cuda: True
  logger: True
  optim: SGD
  keep_prob: 0.5

  # dataset
  num_classes: 61
  train_label_path: data/ai_challenger_pdr2018_trainingset_20180905/AgriculturalDisease_trainingset/AgriculturalDisease_train_annotations.json
  validate_label_path: data/ai_challenger_pdr2018_validationset_20180905/AgriculturalDisease_validationset/AgriculturalDisease_validation_annotations.json
  train_image_prefix: data/ai_challenger_pdr2018_trainingset_20180905/AgriculturalDisease_trainingset/images
  validate_image_prefix: data/ai_challenger_pdr2018_validationset_20180905/AgriculturalDisease_validationset/images

  # dataloader
  worker: 0
  batch_size: 32
  ckpt_path: ckpt
  transform_mean: [0.39883098, 0.48478258, 0.46141425]
  transform_std:  [0.21294028, 0.17201832, 0.1934495]

  # tensorboard
  use_tensorboard: True
  run_path: run

species:
  # train
  epochs: 100
  lr: 0.01
  weight_decay: 0.0001
  momentum: 0.9
  use_cuda: True
  logger: True
  optim: SGD
  keep_prob: 0.5

  # dataset
  num_classes: 10
  train_label_path: data/ai_challenger_pdr2018_trainingset_20180905/AgriculturalDisease_trainingset/AgriculturalDisease_train_mutilayer.json
  validate_label_path: data/ai_challenger_pdr2018_validationset_20180905/AgriculturalDisease_validationset/AgriculturalDisease_validation_mutilayer.json
  train_image_prefix: data/ai_challenger_pdr2018_trainingset_20180905/AgriculturalDisease_trainingset/images
  validate_image_prefix: data/ai_challenger_pdr2018_validationset_20180905/AgriculturalDisease_validationset/images

  # dataloader
  worker: 0
  batch_size: 32
  ckpt_path: multi_task_ckpt/species
  transform_mean: [0.39883098, 0.48478258, 0.46141425]
  transform_std:  [0.21294028, 0.17201832, 0.1934495]

  # tensorboard
  use_tensorboard: True
  run_path: multi_task_run/species


apple:
  # train
  epochs: 100
  lr: 0.005
  weight_decay: 0.0001
  momentum: 0.9
  use_cuda: True
  logger: True
  optim: SGD
  keep_prob: 0.5
  alpha: 0.5
  multitask_num_classes:
    task1: 6
    task2: 4

  # dataset
  num_classes: 6
  train_label_path: data/mutil_task_annotation/apple/new_apple_train.json
  validate_label_path: data/mutil_task_annotation/apple/new_apple_validate.json
  train_image_prefix: data/ai_challenger_pdr2018_trainingset_20180905/AgriculturalDisease_trainingset/images
  validate_image_prefix: data/ai_challenger_pdr2018_validationset_20180905/AgriculturalDisease_validationset/images

  # dataloader
  worker: 0
  batch_size: 32
  ckpt_path: multi_task_ckpt/apple
  transform_mean: [0.39883098, 0.48478258, 0.46141425]
  transform_std:  [0.21294028, 0.17201832, 0.1934495]

  # tensorboard
  use_tensorboard: True
  run_path: multi_task_run/apple


cherry:
  # train
  epochs: 100
  lr: 0.005
  weight_decay: 0.0001
  momentum: 0.9
  use_cuda: True
  logger: True
  optim: SGD
  keep_prob: 0.5
  alpha: 0.5
  multitask_num_classes:
    task1: 3
    task2: 2

  # dataset
  num_classes: 3
  train_label_path: data/mutil_task_annotation/cherry/new_cherry_train.json
  validate_label_path: data/mutil_task_annotation/cherry/new_cherry_validate.json
  train_image_prefix: data/ai_challenger_pdr2018_trainingset_20180905/AgriculturalDisease_trainingset/images
  validate_image_prefix: data/ai_challenger_pdr2018_validationset_20180905/AgriculturalDisease_validationset/images

  # dataloader
  worker: 0
  batch_size: 32
  ckpt_path: multi_task_ckpt/cherry
  transform_mean: [0.39883098, 0.48478258, 0.46141425]
  transform_std:  [0.21294028, 0.17201832, 0.1934495]

  # tensorboard
  use_tensorboard: True
  run_path: multi_task_run/cherry


corn:
  # train
  epochs: 100
  lr: 0.005
  weight_decay: 0.0001
  momentum: 0.9
  use_cuda: True
  logger: True
  optim: SGD
  keep_prob: 0.5
  alpha: 0.5
  multitask_num_classes:
    task1: 8
    task2: 5

  # dataset
  num_classes: 8
  train_label_path: data/mutil_task_annotation/corn/new_corn_train.json
  validate_label_path: data/mutil_task_annotation/corn/new_corn_validate.json
  train_image_prefix: data/ai_challenger_pdr2018_trainingset_20180905/AgriculturalDisease_trainingset/images
  validate_image_prefix: data/ai_challenger_pdr2018_validationset_20180905/AgriculturalDisease_validationset/images

  # dataloader
  worker: 0
  batch_size: 32
  ckpt_path: multi_task_ckpt/corn
  transform_mean: [0.39883098, 0.48478258, 0.46141425]
  transform_std:  [0.21294028, 0.17201832, 0.1934495]

  # tensorboard
  use_tensorboard: True
  run_path: multi_task_run/corn


grape:
  # train
  epochs: 100
  lr: 0.005
  weight_decay: 0.0001
  momentum: 0.9
  use_cuda: True
  logger: True
  optim: SGD
  keep_prob: 0.5
  alpha: 0.5
  multitask_num_classes:
    task1: 7
    task2: 4

  # dataset
  num_classes: 7
  train_label_path: data/mutil_task_annotation/grape/new_grape_train.json
  validate_label_path: data/mutil_task_annotation/grape/new_grape_validate.json
  train_image_prefix: data/ai_challenger_pdr2018_trainingset_20180905/AgriculturalDisease_trainingset/images
  validate_image_prefix: data/ai_challenger_pdr2018_validationset_20180905/AgriculturalDisease_validationset/images

  # dataloader
  worker: 0
  batch_size: 32
  ckpt_path: multi_task_ckpt/grape
  transform_mean: [0.39883098, 0.48478258, 0.46141425]
  transform_std:  [0.21294028, 0.17201832, 0.1934495]

  # tensorboard
  use_tensorboard: True
  run_path: multi_task_run/grape


citrus:
  # train
  epochs: 150
  lr: 0.005
  weight_decay: 0.0001
  momentum: 0.9
  use_cuda: True
  logger: True
  optim: SGD
  keep_prob: 0.35
  alpha: 0.25
  multitask_num_classes:
    task1: 3
    task2: 2

  # dataset
  num_classes: 3
  train_label_path: data/mutil_task_annotation/citrus/new_citrus_train.json
  validate_label_path: data/mutil_task_annotation/citrus/new_citrus_validate.json
  train_image_prefix: data/ai_challenger_pdr2018_trainingset_20180905/AgriculturalDisease_trainingset/images
  validate_image_prefix: data/ai_challenger_pdr2018_validationset_20180905/AgriculturalDisease_validationset/images

  # dataloader
  worker: 0
  batch_size: 32
  ckpt_path: multi_task_ckpt/citrus
  transform_mean: [0.39883098, 0.48478258, 0.46141425]
  transform_std:  [0.21294028, 0.17201832, 0.1934495]

  # tensorboard
  use_tensorboard: True
  run_path: multi_task_run/citrus

peach:
  # train
  epochs: 100
  lr: 0.005
  weight_decay: 0.0001
  momentum: 0.9
  use_cuda: True
  logger: True
  optim: SGD
  keep_prob: 0.5
  alpha: 0.5
  multitask_num_classes:
    task1: 3
    task2: 2

  # dataset
  num_classes: 3
  train_label_path: data/mutil_task_annotation/peach/new_peach_train.json
  validate_label_path: data/mutil_task_annotation/peach/new_peach_validate.json
  train_image_prefix: data/ai_challenger_pdr2018_trainingset_20180905/AgriculturalDisease_trainingset/images
  validate_image_prefix: data/ai_challenger_pdr2018_validationset_20180905/AgriculturalDisease_validationset/images

  # dataloader
  worker: 0
  batch_size: 32
  ckpt_path: multi_task_ckpt/peach
  transform_mean: [0.39883098, 0.48478258, 0.46141425]
  transform_std:  [0.21294028, 0.17201832, 0.1934495]

  # tensorboard
  use_tensorboard: True
  run_path: multi_task_run/peach


pepper:
  # train
  epochs: 100
  lr: 0.005
  weight_decay: 0.0001
  momentum: 0.9
  use_cuda: True
  logger: True
  optim: SGD
  keep_prob: 0.5
  alpha: 0.5
  multitask_num_classes:
    task1: 3
    task2: 2

  # dataset
  num_classes: 3
  train_label_path: data/mutil_task_annotation/pepper/new_pepper_train.json
  validate_label_path: data/mutil_task_annotation/pepper/new_pepper_validate.json
  train_image_prefix: data/ai_challenger_pdr2018_trainingset_20180905/AgriculturalDisease_trainingset/images
  validate_image_prefix: data/ai_challenger_pdr2018_validationset_20180905/AgriculturalDisease_validationset/images

  # dataloader
  worker: 0
  batch_size: 32
  ckpt_path: multi_task_ckpt/pepper
  transform_mean: [0.39883098, 0.48478258, 0.46141425]
  transform_std:  [0.21294028, 0.17201832, 0.1934495]

  # tensorboard
  use_tensorboard: True
  run_path: multi_task_run/pepper


potato:
  # train
  epochs: 100
  lr: 0.005
  weight_decay: 0.0001
  momentum: 0.9
  use_cuda: True
  logger: True
  optim: SGD
  keep_prob: 0.5
  alpha: 0.5
  multitask_num_classes:
    task1: 5
    task2: 3

  # dataset
  num_classes: 5
  train_label_path: data/mutil_task_annotation/potato/new_potato_train.json
  validate_label_path: data/mutil_task_annotation/potato/new_potato_validate.json
  train_image_prefix: data/ai_challenger_pdr2018_trainingset_20180905/AgriculturalDisease_trainingset/images
  validate_image_prefix: data/ai_challenger_pdr2018_validationset_20180905/AgriculturalDisease_validationset/images

  # dataloader
  worker: 0
  batch_size: 32
  ckpt_path: multi_task_ckpt/potato
  transform_mean: [0.39883098, 0.48478258, 0.46141425]
  transform_std:  [0.21294028, 0.17201832, 0.1934495]

  # tensorboard
  use_tensorboard: True
  run_path: multi_task_run/potato


strawberry:
  # train
  epochs: 100
  lr: 0.005
  weight_decay: 0.0001
  momentum: 0.9
  use_cuda: True
  logger: True
  optim: SGD
  keep_prob: 0.5
  alpha: 0.5
  multitask_num_classes:
    task1: 3
    task2: 2

  # dataset
  num_classes: 3
  train_label_path: data/mutil_task_annotation/strawberry/new_strawberry_train.json
  validate_label_path: data/mutil_task_annotation/strawberry/new_strawberry_validate.json
  train_image_prefix: data/ai_challenger_pdr2018_trainingset_20180905/AgriculturalDisease_trainingset/images
  validate_image_prefix: data/ai_challenger_pdr2018_validationset_20180905/AgriculturalDisease_validationset/images

  # dataloader
  worker: 0
  batch_size: 32
  ckpt_path: multi_task_ckpt/strawberry
  transform_mean: [0.39883098, 0.48478258, 0.46141425]
  transform_std:  [0.21294028, 0.17201832, 0.1934495]

  # tensorboard
  use_tensorboard: True
  run_path: multi_task_run/strawberry


tomato:
  # train
  epochs: 150
  lr: 0.005
  weight_decay: 0.0001
  momentum: 0.9
  use_cuda: True
  logger: True
  optim: SGD
  keep_prob: 0.35
  alpha: 0.25
  multitask_num_classes:
    task1: 20
    task2: 11

  # dataset
  num_classes: 20
  train_label_path: data/mutil_task_annotation/tomato/new_tomato_train.json
  validate_label_path: data/mutil_task_annotation/tomato/new_tomato_validate.json
  train_image_prefix: data/ai_challenger_pdr2018_trainingset_20180905/AgriculturalDisease_trainingset/images
  validate_image_prefix: data/ai_challenger_pdr2018_validationset_20180905/AgriculturalDisease_validationset/images

  # dataloader
  worker: 0
  batch_size: 32
  ckpt_path: multi_task_ckpt/tomato
  transform_mean: [0.39883098, 0.48478258, 0.46141425]
  transform_std:  [0.21294028, 0.17201832, 0.1934495]

  # tensorboard
  use_tensorboard: True
  run_path: multi_task_run/tomato